from django.urls import path,include
from . import views
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.test import SimpleTestCase, override_settings
from django.template import RequestContext
from django.conf.urls import handler404



urlpatterns = [
    path('email',views.email,name="email"),
    path('ForgotPassword',views.ForgotPassword,name="ForgotPassword"),
    path('PasswordResetDone',views.PasswordResetDone,name="PasswordResetDone"),
    path('autogradingforgotpassword/<str:sid>',views.autogradingforgotpassword,name="autogradingforgotpassword"),
    path('PasswordUpdate',views.PasswordUpdate,name="PasswordUpdate"),
    path('',views.homepage,name="homepage"),
    path('login',views.loginpage,name="loginpage"),
    path('Dashboard',views.authenticate,name="Dashboard"),
    path('StudentProfile',views.StudentProfile,name="StudentProfile"),
    path('Logout',views.Logout,name="Logout"),
    path('StudentEdit',views.StudentEdit,name="StudentEdit"),
    path('StudentChange',views.StudentChange,name="StudentChange"),
    path('StudentCourseDetails/<str:id>',views.StudentCourseDetails,name="StudentCourseDetails"),
    path('ShowStudentCourseDetails',views.ShowStudentCourseDetails,name="ShowStudentCourseDetails"),
    path('StudentBatch',views.StudentBatch,name="StudentBatch"),
    path('InstructorLogin',views.InstructorLogin,name="InstructorLogin"),
    path('InstructorDashboard',views.InstructorDashboard,name="InstructorDashboard"),
    path('InstructorProfile',views.InstructorProfile,name="InstructorProfile"),
    path('InstructorEdit',views.InstructorEdit,name="InstructorEdit"),
    path('InstructorChange',views.InstructorChange,name="InstructorChange"),
    path('InstructorLogout',views.InstructorLogout,name="InstructorLogout"),
    path('InstructorCourse',views.InstructorCourse,name="InstructorCourse"),
    path('StudentCourse',views.StudentCourse,name="StudentCourse"),
    path('InstructorCourseDelete/<str:id>',views.InstructorCourseDelete,name="InstructorCourseDelete"),
    path('InstructorCourseEdit/<str:id>',views.InstructorCourseEdit,name="InstructorCourseEdit"),
    path('InstructorCourseEditPageShow',views.InstructorCourseEditPageShow,name="InstructorCourseEditPageShow"),
    path('InsructorCourseChange',views.InsructorCourseChange,name="InsructorCourseChange"),
    path('InstructorCourseCreate',views.InstructorCourseCreate,name="InstructorCourseCreate"),
    path('InstuctorCourseNew',views.InstuctorCourseNew,name="InstuctorCourseNew"),
    path('InstructorCourseDetails/<str:id>',views.InstructorCourseDetails,name="InstructorCourseDetails"),
    path('ShowInstructorCourseDetails',views.ShowInstructorCourseDetails,name="ShowInstructorCourseDetails"),
    path('InstructorStudentPage',views.InstructorStudentPage,name="InstructorStudentPage"),  
    path('InstructorStudentView/<str:id>',views.InstructorStudentView,name="InstructorStudentView"),
    path('InstructorStudentViewpage',views.InstructorStudentViewpage,name="InstructorStudentViewpage"),
    path('InstructorCreateStudent',views.InstructorCreateStudent,name="InstructorCreateStudent"),
    path('InstructorUploadFile',views.InstructorUploadFile,name="InstructorUploadFile"),
    path('InstructorAssignCourse/<str:id>',views.InstructorAssignCourse,name="InstructorAssignCourse"),
    path('InstructorAssignCoursepage',views.InstructorAssignCoursepage,name="InstructorAssignCoursepage"),
    path('InstructorAssignCourseToStudent',views.InstructorAssignCourseToStudent,name="InstructorAssignCourseToStudent"),
    path('InstructorStudentDelete/<str:id>',views.InstructorStudentDelete,name="InstructorStudentDelete"),
    path('InstructorStudentDeleteCourseShow/<str:id>',views.InstructorStudentDeleteCourseShow,name="InstructorStudentDeleteCourseShow"),
    path('InstructorStudentDeleteCourseShowpage',views.InstructorStudentDeleteCourseShowpage,name="InstructorStudentDeleteCourseShowpage"),
    path('InstructorAssignCourseToStudentdelete',views.InstructorAssignCourseToStudentdelete,name="InstructorAssignCourseToStudentdelete"),
    path('InstructorBatch',views.InstructorBatch,name="InstructorBatch"),
    path('InstructorCreateBatch',views.InstructorCreateBatch,name="InstructorCreateBatch"),
    path('InstructorCreateBatchSubmit',views.InstructorCreateBatchSubmit,name="InstructorCreateBatchSubmit"),
    path('InstructorBatchEdit/<str:id>',views.InstructorBatchEdit,name="InstructorBatchEdit"),
    path('InstructorBatchEditPageShow',views.InstructorBatchEditPageShow,name="InstructorBatchEditPageShow"),
    path('InstructorEditBatchSubmit',views.InstructorEditBatchSubmit,name="InstructorEditBatchSubmit"),
    path('InstuructorStudentFilter',views.InstuructorStudentFilter,name="InstuructorStudentFilter"),
    path('InstructorDeleteBatch/<str:id>',views.InstructorDeleteBatch,name="InstructorDeleteBatch"),
    path('InstructorStudentFilterBatchCreate',views.InstructorStudentFilterBatchCreate,name="InstructorStudentFilterBatchCreate"),
    path('InstructorStudentFilterBatchEdit',views.InstructorStudentFilterBatchEdit,name="InstructorStudentFilterBatchEdit"),
    path('InstructorBatchShow/<str:id>',views.InstructorBatchShow,name="InstructorBatchShow"),
    path('InstuctorBatchShowPage',views.InstuctorBatchShowPage,name="InstuctorBatchShowPage"),
    path('InstructorSelectedStudentDeleted',views.InstructorSelectedStudentDeleted,name="InstructorSelectedStudentDeleted"),
    path('InstructorCreateNewTopic',views.InstructorCreateNewTopic,name="InstructorCreateNewTopic"),
    path('InstructorSubmitNewTopic',views.InstructorSubmitNewTopic,name="InstructorSubmitNewTopic"),
    path('InstructorTopicView/<str:id>',views.InstructorTopicView,name="InstructorTopicView"),
    path('InstructorTopicEdit/<str:id>',views.InstructorTopicEdit,name="InstructorTopicEdit"),
    path('InstructorSubmitEditTopic',views.InstructorSubmitEditTopic,name="InstructorSubmitEditTopic"),
    path('InstuctorDeleteTopic/<str:id>',views.InstuctorDeleteTopic,name="InstuctorDeleteTopic"),
    path('InsturctorSelectedTopicDelete',views.InsturctorSelectedTopicDelete,name="InsturctorSelectedTopicDelete"),
    path('StudentTopicView/<str:id>',views.StudentTopicView,name="StudentTopicView"),
    path('InstructorCSVDownloadView',views.InstructorCSVDownloadView,name="InstructorCSVDownloadView"),
    path('InstructorDownloadCSV',views.InstructorDownloadCSV,name="InstructorDownloadCSV"),
    path('StudentAssignmentDetails/<str:id>',views.StudentAssignmentDetails,name="StudentAssignmentDetails"),
    path('StudentAssignmentView/<str:id>',views.StudentAssignmentView,name="StudentAssignmentView"),
    path('InstructorAssignmentDetails/<str:id>',views.InstructorAssignmentDetails,name="InstructorAssignmentDetails"),
    path('InstructorCreateAssignment/<str:id>',views.InstructorCreateAssignment,name="InstructorCreateAssignment"),
    path('InstructorSubmitNewAssignment',views.InstructorSubmitNewAssignment,name="InstructorSubmitNewAssignment"),
    path('InstructorAssignmentEdit/<str:aid>/<str:tid>',views.InstructorAssignmentEdit,name="InstructorAssignmentEdit"),
    path('InstructorSubmitEditAssignment',views.InstructorSubmitEditAssignment,name="InstructorSubmitEditAssignment"),
    path('InstructorDeleteAssignment/<str:aid>/<str:tid>',views.InstructorDeleteAssignment,name="InstructorDeleteAssignment"),
    path('InstructorSelectedAssignmentDelete',views.InstructorSelectedAssignmentDelete,name="InstructorSelectedAssignmentDelete"),
    path('InstructorAssignmentView/<str:aid>/<str:tid>',views.InstructorAssignmentView,name="InstructorAssignmentView"),
    path('StudentfinalSubmitcode',views.StudentfinalSubmitcode,name="StudentfinalSubmitcode"),
    path('InstructorTestCaseDetails/<str:aid>',views.InstructorTestCaseDetails,name="InstructorTestCaseDetails"),
    path('InstructorCreateTestcase/<str:aid>',views.InstructorCreateTestcase,name="InstructorCreateTestcase"),
    path('InstructorSubmitNewTestcase',views.InstructorSubmitNewTestcase,name="InstructorSubmitNewTestcase"),
    path('InstructorTestcaseEdit/<str:tid>/<str:aid>',views.InstructorTestcaseEdit,name="InstructorTestcaseEdit"),
    path('InstructorSubmitEditTestcase',views.InstructorSubmitEditTestcase,name="InstructorSubmitEditTestcase"),
    path('InstructorDeleteTestcase/<str:tid>/<str:aid>',views.InstructorDeleteTestcase,name="InstructorDeleteTestcase"),
    path('DeleteAllSelectedTestcase',views.DeleteAllSelectedTestcase,name="DeleteAllSelectedTestcase"),
    path('InstructorStudentAssignmentDetails/<str:aid>',views.InstructorStudentAssignmentDetails,name="InstructorStudentAssignmentDetails"),
    path('InstructorStudentSolutionView/<str:slid>',views.InstructorStudentSolutionView,name="InstructorStudentSolutionView"),
    path('GradeSubmit',views.GradeSubmit,name='GradeSubmit'),
    path('storeeverysecond',views.storeeverysecond,name="storeeverysecond"),
    path('limitover',views.limitover,name="limitover"),
]
