# Generated by Django 3.0.8 on 2020-08-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='instructor',
            field=models.ManyToManyField(to='main.Instructor'),
        ),
    ]
