# Generated by Django 3.0.8 on 2020-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_assignment_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.ManyToManyField(to='main.Batch'),
        ),
    ]
