# Generated by Django 3.0.8 on 2020-08-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_assignment_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='name',
            new_name='assignmentname',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='bname',
            new_name='batchname',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cname',
            new_name='coursename',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lname',
            new_name='languagename',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='studentname',
        ),
    ]
