# Generated by Django 3.0.8 on 2020-08-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200816_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=254)),
                ('output', models.CharField(max_length=254)),
                ('complexity', models.CharField(max_length=254)),
                ('assigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Assignment')),
            ],
        ),
    ]
