# Generated by Django 3.1 on 2020-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Provide Address', max_length=200),
        ),
    ]
