# Generated by Django 3.0.8 on 2020-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discription',
            field=models.CharField(max_length=65535),
        ),
    ]
