# Generated by Django 3.1 on 2020-09-13 07:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200906_0008'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='batchname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
