# Generated by Django 3.1 on 2020-09-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200916_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discription',
        ),
    ]
