# Generated by Django 3.1 on 2020-09-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200916_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='languagename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='assigment',
            new_name='assignment',
        ),
    ]
