# Generated by Django 3.1.1 on 2020-09-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200917_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='complexity',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output',
        ),
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.TextField(default='abc123'),
        ),
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.CharField(default='Not Submit', max_length=254),
        ),
        migrations.AddField(
            model_name='solution',
            name='submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='expectedoutput',
            field=models.TextField(default='set testcase output'),
        ),
        migrations.CreateModel(
            name='TestcaseOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=254)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testcase')),
            ],
        ),
    ]
