# Generated by Django 3.1.1 on 2020-09-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200924_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='defination',
        ),
    ]
