# Generated by Django 3.1.1 on 2020-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_solution_defination'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='email',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
