# Generated by Django 3.1.1 on 2020-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_solution_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='assigment',
            new_name='assignment',
        ),
    ]
