# Generated by Django 3.1.1 on 2020-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200924_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expectedoutput',
            field=models.CharField(max_length=254),
        ),
    ]
