# Generated by Django 3.1.1 on 2020-09-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_testcase_expectedoutput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='comment',
        ),
    ]
