# Generated by Django 3.1.1 on 2020-09-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_solution_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='output',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
