# Generated by Django 3.1.1 on 2020-09-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_testcase_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(),
        ),
    ]
