# Generated by Django 3.1.1 on 2020-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_sampletestcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
