# Generated by Django 3.1.1 on 2020-09-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200925_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletestcase',
            name='name',
        ),
    ]
