# Generated by Django 3.1.1 on 2020-09-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_sampletestcase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseoutput',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
            preserve_default=False,
        ),
    ]
