# Generated by Django 3.1.1 on 2020-09-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_testcaseoutput_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcaseoutput',
            old_name='output',
            new_name='status',
        ),
        migrations.AddField(
            model_name='testcaseoutput',
            name='studentexpectedoutput',
            field=models.TextField(default='Not'),
        ),
        migrations.AddField(
            model_name='testcaseoutput',
            name='studentoutput',
            field=models.TextField(default='Not'),
        ),
    ]
