# Generated by Django 3.1.1 on 2020-09-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200925_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.batch'),
        ),
    ]
