# Generated by Django 3.1.1 on 2020-09-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_solution_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseoutput',
            name='solution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.solution'),
            preserve_default=False,
        ),
    ]
