# Generated by Django 3.1.1 on 2020-09-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseoutput',
            name='percentage',
            field=models.FloatField(default='0'),
        ),
    ]
