# Generated by Django 3.1.1 on 2020-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_testcaseoutput_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcaseoutput',
            name='percentage',
        ),
        migrations.AddField(
            model_name='solution',
            name='percentage',
            field=models.FloatField(default='0'),
        ),
    ]
