# Generated by Django 3.1.1 on 2020-10-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20200928_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='solution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.solution'),
            preserve_default=False,
        ),
    ]
