# Generated by Django 3.1.1 on 2020-10-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_grade_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='percentage',
            field=models.FloatField(default='0'),
        ),
    ]
