# Generated by Django 3.1.1 on 2020-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_grade_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='testcasetype',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
