# Generated by Django 3.1.1 on 2020-10-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_testcase_testcasetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='autograde',
            field=models.CharField(default='A', max_length=254),
        ),
    ]
