# Generated by Django 3.1.1 on 2020-10-14 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_solution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
