# Generated by Django 3.1.1 on 2020-10-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20201014_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySaveAssignmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempcode', models.TextField(default='abc123')),
                ('language', models.CharField(max_length=50)),
                ('counttab', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
