# Generated by Django 3.1.1 on 2020-10-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_temporarysaveassignmentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysaveassignmentdata',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
    ]
