# Generated by Django 3.1.1 on 2020-10-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20201018_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysaveassignmentdata',
            name='language',
            field=models.CharField(max_length=254),
        ),
    ]
