# Generated by Django 3.1.1 on 2020-10-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20201018_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysaveassignmentdata',
            name='counttab',
            field=models.IntegerField(default='0'),
        ),
    ]
